### ISSUE TITLE
[S2 - PBI7] Membuat Komentar pada laman blogs

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#10]
Saya ingin menambahkan, mengedit, dan menghapus tanggapan pada fitur komentar pada blog.

**Comment by ramadwif** [comment]
Use Case Scenario menambahkan komentar
![Screenshot_38](https://user-images.githubusercontent.com/68497378/161434900-a6ea9812-bafe-4de2-b309-7ee92afe56b4.png)

**Comment by ramadwif** [comment]
Use Case Scenario menghapus komentar
![Screenshot_39](https://user-images.githubusercontent.com/68497378/161434920-c8d016da-3969-4675-b646-30d419696aa1.png)

**Comment by ramadwif** [comment]
Activity Diagram
![image13](https://user-images.githubusercontent.com/68497378/161434948-be8a38fd-bd71-4f8d-b092-9d3d78350367.png)

**Comment by ramadwif** [comment]
Mockup
![Blogs (article detail)](https://user-images.githubusercontent.com/68497378/161434984-460d9a4a-c57d-4dc9-883d-77454584398a.png)

**Comment by anandaviamianni** [comment]
Video Sprint Review membuat komentar pada laman blogs, PBI ini merupakan sambungan dari sprint 1
https://user-images.githubusercontent.com/72701447/170819295-bc35923e-91e0-41e3-9409-18a12d596b9f.mp4

**Comment by anandaviamianni** [comment]
Video demo PBI komen
https://user-images.githubusercontent.com/72701447/170860642-738cf4b2-fe56-4a56-b663-6834fcf7ab18.mp4

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170861446-b0d1d679-2b0a-4856-a8e9-b36bd946b695.mp4
