### ISSUE TITLE
[S2 - PBI8] Membuat halaman pethouse (halaman dan details)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#11]
Saya ingin mengakses halaman pethouse (halaman dan details), sehingga saya bisa tahu informasi beberapa lokasi vet yang ada

**Comment by ramadwif** [comment]
Usecase Scenario
![Screenshot_41](https://user-images.githubusercontent.com/68497378/164576391-5c869853-e799-416e-9703-c460a1e8d548.png)

**Comment by ramadwif** [comment]
Activity Diagram
![image10](https://user-images.githubusercontent.com/68497378/164576453-0ef91b6e-2e57-470f-8df8-524854587251.png)

**Comment by ramadwif** [comment]
Mockup PetHouse
![PetHouse](https://user-images.githubusercontent.com/68497378/164576566-5b8e2ef2-bcc8-49ff-a8d1-2839a40bddb5.png)

**Comment by ekkynovrizalam** [comment]
bisa di searching dan filter

**Comment by anandaviamianni** [comment]
Halaman PetHouse
https://user-images.githubusercontent.com/72701447/170623372-582d141f-01dc-478e-b5be-be1ad3caa58c.mp4

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170861952-10e455a8-96a4-44ad-b997-e30a8c07fe07.mp4

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170862274-557b57fd-a3bb-4a95-a025-3d8df95a3c0d.mp4
