### ISSUE TITLE
[S2 - PBI9] Membuat fitur pengelolaan konten oleh admin pada PetHouse (CRUD pethouse dan kategori)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#12]
Saya ingin membuat fitur pengelolaan konten pada halaman PetHouse (CRUD pethouse dan kategori), sehingga saya dapat memberikan beberapa informasi lokasi vet

**Comment by mutiarasalsabila** [comment]
Use case scenario 
![image11 (1)](https://user-images.githubusercontent.com/92173016/164576522-df202c0b-d311-48cc-a455-077ff383e890.png)
![image12 (1)](https://user-images.githubusercontent.com/92173016/164576531-6526cdc3-c6ea-4e1a-a336-a1dbc127ee64.png)
![image18 (1)](https://user-images.githubusercontent.com/92173016/164576535-12f72614-8271-4dfd-a292-86627da35857.png)

**Comment by mutiarasalsabila** [comment]
Usecase scenario
![Screenshot_44 (1)](https://user-images.githubusercontent.com/92173016/164576676-d1c560bb-b32e-4ef2-9100-f22409f4290e.png)
![Screenshot_45 (1)](https://user-images.githubusercontent.com/92173016/164576688-ebb51400-fcac-408f-9046-154bf0384bd9.png)
![Screenshot_46 (1)](https://user-images.githubusercontent.com/92173016/164576692-7e3d730b-5a6e-4808-b548-e974e3b77f0e.png)

**Comment by mutiarasalsabila** [comment]
Mockup
![PetHouse(admin)](https://user-images.githubusercontent.com/92173016/164576758-79194ebd-00bc-4648-8a9f-905dd094cb7f.png)
![PetHouse(admin_detail)](https://user-images.githubusercontent.com/92173016/164576767-5fd5bd30-d795-40dd-98d9-48cc66722675.png)

**Comment by maria-febryanti** [comment]
Yang sudah ditambahkan:
- Front end dan back end Create Pethouse
- Front end dan back end Read Pethouse
- Front end dan back end Update Pethouse
- Front end dan back end Delete Pethouse

Catatan: Apakah perlu membuat fitur untuk Read Pethouse seperti dari sudut pandang user yang diakses dari Dashboard Admin?

**Comment by anandaviamianni** [comment]
![Video]https://user-images.githubusercontent.com/72701447/170820896-ac25b64e-7b22-4178-8538-406957a7e7e2.mp4

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170862952-6585e5be-7bf8-49a8-974b-a74417deab7c.mp4
