### ISSUE TITLE
[S2 - PBI10] Membuat halaman CaRecommend

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#13]
Saya ingin membuat fitur Dashboard, sehingga saya bisa lebih mudah saat mengelola data website

**Comment by ramadwif** [comment]
Use Case Scenario
![CaRecommend](https://user-images.githubusercontent.com/68497378/161435507-d1a2b910-f8dd-4714-a369-9a155b3aa217.png)

**Comment by ramadwif** [comment]
Activity Diagram
![image22](https://user-images.githubusercontent.com/68497378/161435520-5cb50918-4082-49cd-97fa-3692a9d50161.png)

**Comment by ramadwif** [comment]
Mockup menambahkan data peliharaan
![CaRecommend (1)](https://user-images.githubusercontent.com/68497378/161435620-c876513f-c8ae-4327-82c2-35d2bf209034.png)

**Comment by ramadwif** [comment]
Mockup hasil dari CaRecommend
![CaRecommend (Result)](https://user-images.githubusercontent.com/68497378/161435646-2644ae8d-f6a9-4b69-b3a4-527f35795618.png)

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170863451-74f80498-c6cf-49d7-8b08-37edc8eec585.mp4
