### ISSUE TITLE
[S2 - PBI11] Membuat fitur pengelolaan konten oleh admin pada CaRecommend (CRUD CaRecommend dan kategori)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#14]
Saya ingin mengakses halaman CaRecommend, sehingga saya bisa mengetahui rekomendasi makanan untuk peliharaan Saya

**Comment by mutiarasalsabila** [comment]
Mockup
![CaRecommend(admin_details)](https://user-images.githubusercontent.com/92173016/164577081-bece3347-69fb-4207-84ed-0982792f7bcf.png)
![CaRecommend(admin)](https://user-images.githubusercontent.com/92173016/164577087-470e0a62-d7a6-4387-b5f7-4a3f194628d9.png)

**Comment by mutiarasalsabila** [comment]
Usecase Scenario
![Screenshot_44 (1)](https://user-images.githubusercontent.com/92173016/164577756-26fb749d-cb41-4ca3-adf3-0fe9c8f999e5.png)
![Screenshot_45 (1)](https://user-images.githubusercontent.com/92173016/164577759-0ab2c093-d1b8-4d35-886a-491584eb83f4.png)
![Screenshot_46 (1)](https://user-images.githubusercontent.com/92173016/164577766-236d6e06-c744-478a-b32f-7d8b7bd40642.png)

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/170864549-823b1dfb-bb33-4985-a5da-c49727a8ec94.mp4
