### ISSUE TITLE
[S3 - PBI12] Membuat halaman Adopsi (halaman dan details)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#15]
Saya ingin melihat halaman Adopsi (halaman dan details), sehingga saya bisa mengadopsi hewan dari informasi yang didapatkan

**Comment by ekkynovrizalam** [comment]
ditambahkan fitur search berdasarkan jenis

**Comment by anandaviamianni** [comment]
Halaman detail adopsi
Uploading 2022-06-20 21-57-45.mp4…

**Comment by anandaviamianni** [comment]
Halaman detail adopsi
https://user-images.githubusercontent.com/72701447/174630858-6304e3ea-0226-4df0-937b-b529e4853a7c.mp4
