### ISSUE TITLE
[S3 - PBI14] Dashboard Admin

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#17]
Sebagai admin, Saya ingin memiliki halaman dashboard untuk memudahkan pemantauan informasi

**Comment by ekkynovrizalam** [comment]
ditambahkan 2- 3 chart

**Comment by anandaviamianni** [comment]
https://user-images.githubusercontent.com/72701447/174628982-170af4fb-bb87-4df5-a651-3dda964fb533.mp4

**Comment by ramadwif** [comment]
Usecase scenario
<img width="386" alt="dashboard" src="https://user-images.githubusercontent.com/68497378/174743552-a868858e-46df-48cc-88d5-2d85bf7e82dd.PNG">

Activity Diagram
![Diagram RPL(1)(1) vpd-Admin Melihat Dashboard](https://user-images.githubusercontent.com/68497378/174744193-8ea6f36a-ef92-4477-ba5e-44f9baf5b5c5.png)

**Comment by mutiarasalsabila** [comment]
https://user-images.githubusercontent.com/92173016/174845946-dcde3904-2ec2-4f86-8b1b-4d40e60401cb.mp4
