### ISSUE TITLE
[S3 - PBI15] Membuat Laman About Us

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#18]
Saya ingin membuat halaman About Us yang menampilkan informasi mengenai The Paws

**Comment by ekkynovrizalam** [comment]
ditambahkan fitur edit konten di sisi admin

**Comment by ramadwif** [comment]
About Us
![About Us](https://user-images.githubusercontent.com/68497378/174733199-55c78bd4-13b4-48bd-ac92-79cc4f0818dc.png)
Admin About Us
![About Us(admin)](https://user-images.githubusercontent.com/68497378/174733282-15e5b455-4bc6-4723-9972-da4430160dcb.png)

**Comment by ramadwif** [comment]
Use Case Scenario
![AboutUs](https://user-images.githubusercontent.com/68497378/174738078-e630a9dd-1fa4-4c45-b1ae-c86b75836bb0.png)

**Comment by ramadwif** [comment]
Activity Diagram
![Aboutus (1)](https://user-images.githubusercontent.com/68497378/174740614-85005d17-365f-45a7-bc69-fd4398ca47ac.png)
