### ISSUE TITLE
[S1 - PBI2] Membuat Registrasi dan Login

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#5]
Saya ingin melakukan Registrasi dan Login untuk membuat akun, , sehingga saya dapat membuat akun untuk mengakses website

**Comment by ramadwif** [comment]
Mockup Login
![The Paws-03](https://user-images.githubusercontent.com/68497378/160974688-12df688c-b379-4d17-b363-53ff5776b23c.jpg)
