### ISSUE TITLE
[S1 - PBI4] Membuat fitur pengelolaan kategori oleh admin(CRUD)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#7]
Saya sebagai admin ingin mengelola kategori-kategori apa saja yang terdapat pada website

**Comment by ekkynovrizalam** [comment]
harus dinamis

**Comment by mutiarasalsabila** [comment]
Activity Diagram Admin menambah kategori
<img width="389" alt="menambah kategori" src="https://user-images.githubusercontent.com/92173016/161189418-b26fe249-e3e5-4e76-9d1e-0327de67fa1d.PNG">
Activity Diagram Admin mengupdate kategori
<img width="383" alt="Memperbarui kategori" src="https://user-images.githubusercontent.com/92173016/161189456-fe724cde-cd80-4b8f-bde9-5f3e78c51634.PNG">
Activity Diagram Admin menghapus kategori
<img width="384" alt="Menghapus kategori" src="https://user-images.githubusercontent.com/92173016/161189489-98b0559c-9433-4e2a-9f7a-705ee2efad87.PNG">

**Comment by mutiarasalsabila** [comment]
Activity Diagram Admin menambah kategori
![Admin - Create - pengelolaan kategori](https://user-images.githubusercontent.com/92173016/161189911-e294dedf-7573-46a3-a255-382f7eab2836.png)
Activity Diagram Admin mengupdate  kategori
![Admin - Update - pengelolaan kategori](https://user-images.githubusercontent.com/92173016/161190018-ecdd330f-8fbf-4a20-8936-8f15c3d604ed.png)
Activity Diagram Admin menghapus  kategori
![Admin - Delete - pengelolaan kategori](https://user-images.githubusercontent.com/92173016/161190076-e71345e8-facc-4fd4-a8cf-a0ba698961b5.png)

**Comment by mutiarasalsabila** [comment]
Mockup 
![Data Category](https://user-images.githubusercontent.com/92173016/161190282-13cb164c-d309-40a0-b8b8-2795cc8ce348.png)
![MODAL Tambah Kategori](https://user-images.githubusercontent.com/92173016/161190288-c2e8b089-87aa-401d-90a6-df4108c59129.png)
