### ISSUE TITLE
[S1 - PBI6] Membuat halaman blogs (halaman dan details)

### ISSUE THREAD

**Issue by anandaviamianni** [SI-RPL-2022/SI4302_F_ThePaws#9]
Saya ingin melihat artikel melalui halaman blogs (halaman dan details), sehingga saya bisa membaca informasi melalui blogs

**Comment by anandaviamianni** [comment]
Activity Diagram

![The Paws-01](https://user-images.githubusercontent.com/72701447/161188433-0fc2595b-3e4a-4229-9e63-c4302c2915bc.png)

**Comment by anandaviamianni** [comment]
Mockup blog

![The Paws-01](https://user-images.githubusercontent.com/72701447/161188929-e65b6fb7-6d07-48ca-91c8-cd49d0d1e021.png)

**Comment by ramadwif** [comment]
Mockup Blogs (article details)
![Blogs (article detail)](https://user-images.githubusercontent.com/68497378/161434784-0d501311-8f8b-47df-83a1-0741238db71f.png)

**Comment by ekkynovrizalam** [comment]
pengganti searching adalah tombol kategori di bagian kanan bisa diklik dan filter blog yang ditampilkan sesuai kategori

**Comment by ramadwif** [comment]
Video fitur filter pada halaman Blogs

https://user-images.githubusercontent.com/68497378/163796771-9947f4c9-d1f1-4eec-8f99-4c5fd4ff8cda.mp4
